### ISSUE TITLE
Use --strict flag?

### ISSUE THREAD

**Issue by jclem** [fazibear/codeclimate-credo#2]
Since [--strict can't be specified in .credo.exs](https://github.com/rrrene/credo/issues/168), is there a way to pass the flag in .codeclimate.yml with this engine?

**Comment by dblandin** [comment]
I could see this working as an option within the `.codeclimate.yml` configuration:

``` yaml
---
engines:
  credo:
    enabled: true
    channel: beta
    config:
      strict: true
ratings:
  paths:
  - "**.ex"
  - "**.exs"
```
