### ISSUE TITLE
Doesn't work with Phoenix?

### ISSUE THREAD

**Issue by Kitton** [fazibear/codeclimate-credo#6]
New pure project generated with Phoenix

**.codeclimate.yml**
```
---
engines:
  credo:
    enabled: true
    channel: "beta"
    config:
      strict: true
ratings:
  paths:
  - "**.ex"
  - "**.exs"

```

No **.credo.exs** file.

```

➜ codeclimate analyze
Starting analysis
Running credo: Done!

Analysis complete! Found 0 issues.
➜  mix credo
Checking 15 source files ...

  Code Readability                                                              
┃ 
┃ [R] → Modules should have a @moduledoc tag.
┃       lib/phx_hello/application.ex:1:11 #(PhxHello.Application)

Please report incorrect results: https://github.com/rrrene/credo/issues

Analysis took 0.3 seconds (0.06s to load, 0.2s running checks)
35 mods/funs, found 1 code readability issue.

```

The same on a real project with a different set of issues.
Also I have tried to add Phoenix project on the website - the same result, an empty set of issues.
Not sure if it's related to https://github.com/fazibear/codeclimate-credo/issues/3. Any ideas?
